---
- id: 1
  name: twitter
  app: Twitters
  settings:
    username: test
    password: password
  shortcut: '*tw'
- id: 2
  name: tumblr
  app: Tumblr
  settings:
    username: test
    password: password
  shortcut: '*tum'