---
- id: 1
  name: twitter
  app_type: Twitter
  settings:
    username: test
    password: password
  shortcut: '*tw'
- id: 2
  name: tumblr
  app_type: Tumblr
  settings:
    username: test
    password: password
  shortcut: '*tum'